### ISSUE TITLE
is this the official repo?

### ISSUE THREAD

**Issue by UnixJunkie** [pveber/ocaml-r#4]
Why is it not in opam?

**Comment by pveber** [comment]
AFAIK I'm the only one maintaining the code base, but I do very little about it (actually the minimum so that I can still use the library). The main reason why the library is not released on opam is that it needs a major modification, that would significantly modify the API. So I've postponed the release until this enhancement is done, but it's been years now that I didn't have the time for this and it's not going to change any time soon. The modification I refer to is the fact that numeric vector on the R side are represented as `float list` on the ocaml side, instead of `float array`.

**Comment by pveber** [comment]
This change has been done since then, I'm therefore releasing the library a bit more officially.
